variables:
  FF_USE_FASTZIP: 1
  FF_SCRIPT_SECTIONS: 1
  PROJECT_NAME: ecom-client
  PROJECT_CONFIG: '/${APPLICATION_ENV}/${PROJECT_NAME}'
  BIZ_ENV: ${ROOT_BIZ_ENV}
  PACKAGE_INSTALL: 'yarn'
  PACKAGE_BUILD: 'yarn build'
  BUILD_DIR: 'dist'
  SERVICE_NAME: 'ecom-client-dev'
  DISCARD_DEPLOY_FORKS: 'nepal|alston|indonesia' # deployment will be discarded to the fork name mentioned here

stages:
  - test
  - build-dev
  - deploy-dev
  - build-stage
  - deploy-stage
  - build-prod
  - deploy-prod

image: registry.gitlab.com/innovate-tech/infrasturcture/templates/nodejs-18

include:
  - project: 'innovate-tech/infrasturcture/templates'
    ref: main
    file: 'frontend/build.yaml'
    rules:
      - if: $CI_PIPELINE_SOURCE != "merge_request_event"
  - project: 'innovate-tech/infrasturcture/templates'
    ref: main
    file: 'security/trivy-frontend.yaml'
